"""Realtime copilot endpoints — PRD §7.5.

A-8 wired the POST stub with the `require_adult` compliance gate.
A-15 replaced the 501 with the real handler that mints a copilot_id,
persists a `pending` row, and returns the canonical WebSocket URL the
client connects to.
A-16 shipped the WS endpoint at that URL with an echo-loop scaffold.
A-18 replaced the echo with the real audio bridge: bytes frames carry
audio, the text control frame `{"type":"audio_end"}` terminates each
utterance, and the server emits `asr_partial` / `asr_final` events
back through `ASRProvider`.
A-19 chained `ModerationService` after each `asr_final` so finalized
transcripts go through the same cascading red-line scoring
`POST /v1/moderation/check` uses; a `moderation` event follows the
`asr_final` so the client can react.
A-20 wired `LLMRouter`. When the moderation verdict is `allow` or
`warn`, a Coach K hint is generated in the background and streamed
back as `hint_delta` / `hint_done` events. `redirect` and `block`
verdicts gate the LLM call entirely — no tokens are spent on
content the platform won't surface.
A-21 (this module) attaches a Langfuse trace per utterance:
`copilot_utterance`-named, with `transcribe` / `moderate` /
`coach_hint` child generations so analysts can see the full pipeline
on the Langfuse UI. When LANGFUSE_PUBLIC_KEY/SECRET_KEY is unset the
trace wrapper degrades to no-op so dev runs keep working.

Compliance attach point (POST)
------------------------------
`require_adult` chains through `require_age_set`, so the failure
ladder is:
  * No token                  → 401 UNAUTHORIZED
  * Token, age_set=False      → 403 AGE_REQUIRED
  * Token, is_minor=True      → 403 MINOR_FORBIDDEN
  * Token, adult, age set     → 200 (real handler runs)

R-15 in PRD §11.2 (未成年人误用副驾) is the load-bearing constraint
that makes the minor gate non-negotiable.

WebSocket auth model (transitional, A-16)
-----------------------------------------
The WS endpoint does NOT re-run `require_adult`. The capability ticket
is the freshly-minted `copilot_id` itself: only a `pending` row can
connect, and `pending` rows can only exist if the POST cleared the
adult gate. A future PR will tighten this with a JWT-bearing
subprotocol once B's client is comfortable signing the WS upgrade.
The 64 bits of entropy on `copilot_id` (16 hex chars) keeps brute-force
mining of valid ids out of reach for v0.

WS protocol — A-18 / A-19 / A-20
--------------------------------
Once connected, the client–server protocol is:

    Client → Server
        binary frame: PCM/Opus audio chunk for the current utterance
        text frame:   JSON `{"type":"audio_end"}` to finalize the
                      current utterance; any other text is ignored

    Server → Client
        text frame:   `{"type":"asr_partial","text":...}`
                      cumulative interim transcript, may revise
        text frame:   `{"type":"asr_final","text":...}`
                      exactly one per utterance, terminal transcript
        text frame:   `{"type":"moderation","verdict":"allow"|"warn"|
                       "redirect"|"block","categories":[...],
                       "score":0..1,"redirect_resource":null|{...}}`
                      follows asr_final when final text is non-empty
        text frame:   `{"type":"hint_delta","text":"chunk"}`
                      LLM token chunk (one per delta from the router)
        text frame:   `{"type":"hint_done","text":"<full text>"}`
                      terminal hint event with the joined transcript
        text frame:   `{"type":"hint_error","message":"..."}`
                      LLM call failed (auth / timeout / upstream)

Hint events only emit when the moderation verdict is `allow` or
`warn`. Hints are generated by a background task, so a slow LLM
doesn't block the next utterance — events for utterance N+1 may
interleave with hint events for utterance N, and the client demuxes
on `type`. The handler awaits all in-flight hint tasks in `finally`
before flipping the row to `ended`.
"""

from __future__ import annotations

import asyncio
import json
import time
from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import Any

import structlog
from fastapi import APIRouter, Depends, WebSocket
from langfuse import Langfuse
from starlette.websockets import WebSocketDisconnect

from app.asr import (
    ASRAuthError,
    ASRError,
    ASRMalformedResponseError,
    ASRProvider,
    ASRTimeoutError,
    ASRUpstreamError,
    get_asr_provider,
)
from app.llm import LLMProvider
from app.llm.factory import get_llm_router
from app.observability.langfuse import (
    TurnTrace,
    begin_copilot_trace,
    get_langfuse_client,
)
from app.routes.v1.copilot_hint import (
    elapsed_ms,
    moderate_and_emit,
    stream_coach_hint,
)
from app.schemas.copilot import CreateCopilotSessionRequest, CreateCopilotSessionResponse
from app.schemas.moderation import ModerationVerdict
from app.services.auth import CurrentUser, require_adult
from app.services.copilot import CopilotService, get_copilot_service
from app.services.copilot.service import (
    CopilotSessionNotFound,
    CopilotSessionUnavailable,
)
from app.services.moderation import (
    ModerationService,
    get_moderation_service,
)

# Stable model labels surfaced on the Langfuse generation rows. The
# moderation pipeline can swap backends per request (CascadingBackend
# falls back local→cloud) so we use a fixed label rather than peeking
# at `_backend.name`.
_MOD_GENERATION_MODEL = "moderation_pipeline"

logger = structlog.get_logger(__name__)

router = APIRouter(prefix="/copilot", tags=["copilot"])

# Application-defined close codes (RFC 6455 §7.4.2 reserves 4000–4999
# for app use). 4404 / 4409 mirror the HTTP status semantics so any
# client that already understands "404 / 409 = retry policy" can map
# them mechanically without a per-feature lookup table.
_WS_UNKNOWN_COPILOT_CODE = 4404
_WS_SESSION_ALREADY_USED_CODE = 4409

_AUDIO_END_TYPE = "audio_end"

# Upper bound on the transcript we moderate + feed the coach hint, in
# characters. Mirrors `ModerationCheckRequest.content`'s max_length so an
# over-long utterance is clamped instead of raising a `ValidationError`
# that would crash the WS handler and drop the client's mic. Real ASR
# utterances are short; this only bites pathological streams (e.g. the
# dummy ASR echoing raw PCM bytes during local dev).
_MAX_TRANSCRIPT_CHARS = 8000

# Verdicts that pass the moderation gate and let the LLM hint emit.
# `redirect` already surfaces a crisis-line resource via the moderation
# event itself; `block` is a hard stop. Both suppress hint generation
# so we never spend tokens on content we wouldn't surface.
_HINT_ALLOWED_VERDICTS: frozenset[ModerationVerdict] = frozenset({"allow", "warn"})


@router.post(
    "/sessions",
    response_model=CreateCopilotSessionResponse,
    summary="Create a realtime copilot session",
    responses={
        401: {"description": "Missing or invalid bearer token."},
        403: {
            "description": (
                "`AGE_REQUIRED` if the JWT lacks `age_set=true`; "
                "`MINOR_FORBIDDEN` if the caller is under 18. PRD §1.5 / R-15."
            ),
        },
    },
)
async def create_copilot_session(
    payload: CreateCopilotSessionRequest,
    current: CurrentUser = Depends(require_adult),
    service: CopilotService = Depends(get_copilot_service),
) -> CreateCopilotSessionResponse:
    """Mint a copilot session row and return the WebSocket URL.

    No LLM call, no moderation in this handler — copilot is
    adult-only (gate-enforced) and the audio + transcript moderation
    runs in the WS handler against each `asr_final` (A-19). A-15
    persists the session intent so the WS endpoint can look it up
    on connect.
    """
    result = await service.create_session(
        scenario_hint=payload.scenario_hint,
        privacy_level=payload.privacy_level,
        user_id=current.user_id,
    )
    return CreateCopilotSessionResponse(
        copilot_id=result.record.copilot_id,
        ws_url=result.ws_url,
    )


@router.websocket("/sessions/{copilot_id}/stream")
async def copilot_stream(
    websocket: WebSocket,
    copilot_id: str,
    service: CopilotService = Depends(get_copilot_service),
    asr_provider: ASRProvider = Depends(get_asr_provider),
    moderation_service: ModerationService = Depends(get_moderation_service),
    llm_router: LLMProvider = Depends(get_llm_router),
    langfuse_client: Langfuse | None = Depends(get_langfuse_client),
) -> None:
    """Realtime copilot stream — audio bridge + moderation + Coach K hints.

    Lifecycle
    ---------
    1. Accept the WS upgrade unconditionally — we always accept first
       so failures send a structured close frame instead of the opaque
       `403` that pre-accept rejection would yield. Clients then know
       how to map our 4xxx codes.
    2. `connect_session` flips the row to `connected` (or raises one
       of the two error types below). The returned record carries the
       JWT-derived `user_id` for moderation audit attribution and the
       `scenario_hint` we feed to Coach K's prompt.
    3. Multi-utterance loop: for each utterance, run the audio bridge
       until `audio_end` or disconnect, moderate the final text, and
       (if verdict allows) spawn a background hint task.
    4. When the NEXT utterance completes, any still-in-flight hints
       from prior utterances are cancelled (A-22) — they're no
       longer relevant once the user has moved on. Tokens already
       streamed to the client stay visible; the missing `hint_done`
       is the client's signal that the prior hint was superseded.
    5. Client disconnect (or any exception) drains in-flight hint
       tasks, then runs `end_session` — flips the row to `ended` and
       stamps `ended_at`.

    `end_session` is only reachable when `connect_session` succeeded:
    the two `except` arms above `close()` and `return` early so an
    unknown-id probe never falls through into the multi-utterance loop
    and never triggers the cleanup `finally`.
    """
    await websocket.accept()
    record = None
    try:
        record = await service.connect_session(copilot_id)
    except CopilotSessionNotFound:
        await websocket.close(
            code=_WS_UNKNOWN_COPILOT_CODE,
            reason="UNKNOWN_COPILOT",
        )
        return
    except CopilotSessionUnavailable:
        await websocket.close(
            code=_WS_SESSION_ALREADY_USED_CODE,
            reason="SESSION_ALREADY_USED",
        )
        return

    hint_tasks: set[asyncio.Task[None]] = set()
    try:
        while True:
            result, trace = await _run_one_utterance(
                websocket,
                asr_provider=asr_provider,
                moderation_service=moderation_service,
                copilot_id=copilot_id,
                user_id=record.user_id,
                scenario_hint=record.scenario_hint,
                privacy_level=record.privacy_level,
                langfuse_client=langfuse_client,
            )
            # The user has moved on to a new utterance; any prior
            # hint that hasn't finished is now stale. Cancel here so
            # the LLM stream stops billing tokens and no further
            # `hint_delta` / `hint_done` events arrive for content
            # the user no longer cares about.
            await _cancel_in_flight_hints(hint_tasks, copilot_id=copilot_id)
            if _should_spawn_hint(result):
                task = asyncio.create_task(
                    stream_coach_hint(
                        websocket,
                        llm_router=llm_router,
                        moderation_service=moderation_service,
                        scenario_hint=record.scenario_hint,
                        user_input=result.final_text,
                        copilot_id=copilot_id,
                        user_id=record.user_id,
                        trace=trace,
                    )
                )
                hint_tasks.add(task)
                task.add_done_callback(hint_tasks.discard)
    except WebSocketDisconnect:
        logger.info("copilot_ws_disconnected", copilot_id=copilot_id)
    finally:
        # Final drain — at session end, prefer cancelling the
        # in-flight LLM call over waiting for it to complete: the user
        # is gone, the WS is closing, no one will see the tokens.
        await _cancel_in_flight_hints(hint_tasks, copilot_id=copilot_id)
        await service.end_session(copilot_id)


async def _cancel_in_flight_hints(
    hint_tasks: set[asyncio.Task[None]],
    *,
    copilot_id: str,
) -> None:
    """Cancel and drain all not-yet-done hint tasks.

    Called between utterances (the new audio supersedes the prior
    hint) and once more in the outer `finally` (session is ending).
    Done tasks are skipped — `task.cancel()` on a finished task is
    a no-op, but `gather` would still re-raise their stored
    exceptions; filtering keeps the gather call clean.

    Errors from cancelled tasks are swallowed: `CancelledError` is
    expected, and any other late-arriving exception was already
    logged by `stream_coach_hint`'s own try/except.
    """
    pending = [t for t in hint_tasks if not t.done()]
    if not pending:
        return
    for task in pending:
        task.cancel()
    logger.info(
        "copilot_hint_tasks_cancelled",
        copilot_id=copilot_id,
        count=len(pending),
    )
    await asyncio.gather(*pending, return_exceptions=True)


@dataclass(frozen=True)
class _UtteranceResult:
    """Outcome of one `_run_one_utterance` cycle.

    `verdict` is None when the final text was empty (no moderation
    ran, see PRD-aligned skip in `_run_one_utterance`). Callers gate
    on `verdict in _HINT_ALLOWED_VERDICTS` rather than checking
    `final_text` directly so the gate stays in one place.
    """

    final_text: str
    verdict: ModerationVerdict | None


def _should_spawn_hint(result: _UtteranceResult) -> bool:
    return bool(result.final_text) and result.verdict in _HINT_ALLOWED_VERDICTS


async def _run_one_utterance(
    websocket: WebSocket,
    *,
    asr_provider: ASRProvider,
    moderation_service: ModerationService,
    copilot_id: str,
    user_id: str,
    scenario_hint: str,
    privacy_level: str,
    langfuse_client: Langfuse | None,
) -> tuple[_UtteranceResult, TurnTrace]:
    """Receive audio bytes + an `audio_end` control frame, transcribe,
    emit `asr_partial` / `asr_final` events, then run moderation on
    the finalized text and emit a `moderation` event. Returns
    `(_UtteranceResult, TurnTrace)`: the result so the caller can
    decide whether to spawn a hint task, and the trace so the hint
    task can record its generation under the same parent.

    Raises `WebSocketDisconnect` if the client disconnects
    mid-utterance (the trace is marked failed and re-raised).

    Concurrency: feeder and streamer run in parallel via
    `asyncio.gather` because `DummyASRProvider` (and any real vendor)
    yields partials as chunks arrive — we can't feed first then
    stream, or partials would back up unbounded. `gather` cancels the
    other task on first exception, which is the right behavior for a
    `WebSocketDisconnect` from either side.

    Moderation runs serially after the audio loop completes. Hint
    generation (when applicable) is spawned by the caller as a
    background task, so a slow LLM doesn't block the next utterance.
    The hint task records its own generation on the trace; the trace
    output is set here based on the moderation outcome, and the hint
    arrives later as an additional child span (Langfuse handles that
    cleanly — `update(output=...)` doesn't close the trace).
    """
    audio_queue: asyncio.Queue[bytes | None] = asyncio.Queue()

    async def audio_iter() -> AsyncIterator[bytes]:
        while True:
            chunk = await audio_queue.get()
            if chunk is None:
                return
            yield chunk

    feeder = _feed_audio(websocket, audio_queue, copilot_id)
    streamer = _stream_asr_events(websocket, asr_provider, audio_iter(), copilot_id)
    # If the client disconnects mid-utterance, gather raises
    # WebSocketDisconnect from the feeder; we do NOT mint a trace
    # for that case — the outer handler logs the disconnect and
    # an empty Langfuse trace would just be noise.
    _, (final_text, asr_error_type) = await asyncio.gather(feeder, streamer)

    # Clamp before moderation/hint so a pathologically long transcript
    # can't trip ModerationCheckRequest's max_length and crash the WS.
    if len(final_text) > _MAX_TRANSCRIPT_CHARS:
        logger.warning(
            "copilot_transcript_clamped",
            copilot_id=copilot_id,
            original_chars=len(final_text),
            kept_chars=_MAX_TRANSCRIPT_CHARS,
        )
        final_text = final_text[:_MAX_TRANSCRIPT_CHARS]

    trace = begin_copilot_trace(
        langfuse_client,
        input={"scenario_hint": scenario_hint},
        # `copilot_id` is promoted to Langfuse's top-level session_id
        # (A-23) so every utterance in one WS connection lands under
        # the same Langfuse session. Keep `user_id` in metadata for
        # cross-session filtering.
        metadata={"user_id": user_id},
        session_id=copilot_id,
        # A-40: trace_id + user_id let `record_generation` schedule
        # the per-call DB insert into `llm_calls`. `copilot_id` doubles
        # as the per-utterance trace correlator (same value Langfuse
        # already sees as session_id); copilot's surface is hardcoded
        # inside `begin_copilot_trace`.
        trace_id=copilot_id,
        user_id=user_id,
        # A-24: surface + privacy tags at creation. Verdict tag is
        # added after moderation runs (below). `minor:false` is
        # implicit and intentionally NOT tagged — copilot is
        # adult-only by R-15.
        tags=[
            "surface:copilot",
            f"privacy:{privacy_level}",
        ],
    )
    # A-31: surface the ASR outcome on the trace so a failed
    # transcription is distinguishable from an actual empty utterance
    # (both currently look the same downstream — final_text=""). Two
    # tags so analysts can filter just the failed ones AND see the
    # error class without parsing logs.
    asr_status = "failed" if asr_error_type is not None else "ok"
    asr_status_tags = [f"asr_status:{asr_status}"]
    if asr_error_type is not None:
        asr_status_tags.append(f"asr_error:{asr_error_type}")
    trace.add_tags(asr_status_tags)
    trace.record_generation(
        name="transcribe",
        model=asr_provider.name,
        input={"copilot_id": copilot_id},
        output={"text": final_text, "char_count": len(final_text)},
    )

    if not final_text:
        trace.finish(output={"final_text": "", "verdict": None})
        return _UtteranceResult(final_text="", verdict=None), trace

    mod_started_at = time.perf_counter()
    decision, verdict_label = await moderate_and_emit(
        websocket,
        moderation_service=moderation_service,
        text=final_text,
        copilot_id=copilot_id,
        user_id=user_id,
    )
    # P0 waterfall: input-moderation cost. Small on the local dict
    # backend, but worth pinning so a cloud-backend swap that adds a
    # network round-trip here shows up in the same dashboard.
    logger.info(
        "copilot_input_moderation_latency",
        copilot_id=copilot_id,
        input_moderation_ms=elapsed_ms(mod_started_at, time.perf_counter()),
    )
    if decision is not None:
        trace.record_generation(
            name="moderate",
            model=_MOD_GENERATION_MODEL,
            input={"text": final_text},
            output={
                "verdict": decision.verdict,
                "score": decision.score,
                "categories": list(decision.categories),
            },
        )
    # A-24/A-32/A-37: verdict_input tag. Decoupled from `decision is
    # not None` in A-37 so a backend outage still surfaces as
    # `verdict_input:backend_failed` even though no Decision exists.
    # Other catch-all failures (verdict_label is None) stay untagged
    # — those are bugs and should be investigated via the exception
    # log, not silently bucketed as `backend_failed`.
    if verdict_label is not None:
        trace.add_tags([f"verdict_input:{verdict_label}"])

    verdict = decision.verdict if decision is not None else None
    trace.finish(output={"final_text": final_text, "verdict": verdict})
    return _UtteranceResult(final_text=final_text, verdict=verdict), trace


async def _feed_audio(
    websocket: WebSocket,
    audio_queue: asyncio.Queue[bytes | None],
    copilot_id: str,
) -> None:
    """Pull frames off the WS and feed audio bytes into the queue.
    Returns when `audio_end` arrives; raises `WebSocketDisconnect` on
    client disconnect (and puts a None sentinel so the ASR iterator
    unblocks before we propagate)."""
    while True:
        msg = await websocket.receive()
        if msg["type"] == "websocket.disconnect":
            await audio_queue.put(None)
            raise WebSocketDisconnect(code=msg.get("code", 1000))

        chunk: bytes | None = msg.get("bytes")
        if chunk is not None:
            await audio_queue.put(chunk)
            continue

        text: str | None = msg.get("text")
        if text is not None and _is_audio_end(text):
            await audio_queue.put(None)
            return
        if text is not None:
            logger.debug(
                "copilot_ws_unknown_text_frame",
                copilot_id=copilot_id,
                preview=text[:80],
            )


async def _stream_asr_events(
    websocket: WebSocket,
    asr_provider: ASRProvider,
    audio_chunks: AsyncIterator[bytes],
    copilot_id: str,
) -> tuple[str, str | None]:
    """Consume the ASR provider's event stream, forward each event as
    a typed WS envelope, and return `(final_text, error_type)` so the
    caller can both gate moderation/hint AND tag the Langfuse trace.

    On any `ASRError` (auth / timeout / upstream) we emit a single
    `asr_error` frame with an opaque user-facing message and return
    `("", <error_type>)` where `error_type` is one of
    `"auth" | "timeout" | "upstream"`. The empty `final_text` tells
    the caller to treat the utterance as a no-op (skip moderation +
    skip hint generation); the `error_type` drives the
    `asr_error:{type}` Langfuse tag so analysts can triage outages
    by class without parsing structured logs.

    Vendor-specific details (status codes, internal messages) are
    kept out of the client-facing payload — they'd leak provider
    fingerprints to anyone with browser devtools. The structured log
    has the full detail for ops.
    """
    final_text = ""
    try:
        async for event in asr_provider.transcribe_stream(audio_chunks):
            await websocket.send_json(
                {
                    "type": f"asr_{event.kind}",
                    "text": event.text,
                }
            )
            if event.kind == "final":
                final_text = event.text
    except ASRError as exc:
        error_type = _classify_asr_error(exc)
        logger.warning(
            "copilot_ws_asr_failed",
            copilot_id=copilot_id,
            provider=asr_provider.name,
            error_type=type(exc).__name__,
            error_class=error_type,
            error=str(exc),
        )
        await websocket.send_json({"type": "asr_error", "message": "transcription unavailable"})
        return "", error_type
    logger.info(
        "copilot_ws_utterance_complete",
        copilot_id=copilot_id,
        provider=asr_provider.name,
        final_char_count=len(final_text),
    )
    return final_text, None


def _classify_asr_error(exc: ASRError) -> str:
    """Map a typed `ASRError` to the short label used in trace tags.

    A-31 introduced three buckets: `auth` / `timeout` / `upstream`.
    A-38 subdivides the `upstream` bucket so analysts can split
    triage paths that need different responses:

      * `auth`               — token expired/revoked, AK/secret wrong, IAM denied
      * `timeout`            — vendor took longer than our budget
      * `upstream_malformed` — vendor returned 200 but body shape wrong
                               (usually a vendor SDK / API drift; tell vendor)
      * `upstream_5xx`       — vendor returned 5xx (vendor is down; retry policy)
      * `upstream_4xx`       — vendor returned 4xx (our request is wrong;
                               fix our request, retry won't help)
      * `upstream_unknown`   — no HTTP status_code captured (transport-level
                               error like WS connection abort, DNS failure)

    Order matters — `ASRMalformedResponseError` subclasses
    `ASRUpstreamError`, and both `ASRAuthError`/`ASRTimeoutError`
    subclass the base `ASRError`. The isinstance ladder checks
    most-specific-first.

    Breaking change vs A-31: the bare `upstream` tag no longer
    exists; analyst dashboards filtering `asr_error:upstream`
    must move to `asr_error:upstream_*` (prefix match).
    """
    if isinstance(exc, ASRAuthError):
        return "auth"
    if isinstance(exc, ASRTimeoutError):
        return "timeout"
    if isinstance(exc, ASRMalformedResponseError):
        return "upstream_malformed"
    if isinstance(exc, ASRUpstreamError):
        if exc.status_code is not None:
            if 500 <= exc.status_code < 600:
                return "upstream_5xx"
            if 400 <= exc.status_code < 500:
                return "upstream_4xx"
        return "upstream_unknown"
    return "upstream_unknown"


def _is_audio_end(raw: str) -> bool:
    """`{"type":"audio_end"}` is the only text control frame the
    bridge currently recognises. Robust against malformed JSON and
    unexpected shapes — anything we don't understand is silently
    dropped at the call site."""
    try:
        data: Any = json.loads(raw)
    except json.JSONDecodeError:
        return False
    return isinstance(data, dict) and data.get("type") == _AUDIO_END_TYPE
