"""Realtime copilot endpoints — PRD §7.5.

A-8 wired the POST stub with the `require_adult` compliance gate.
A-15 replaced the 501 with the real handler that mints a copilot_id,
persists a `pending` row, and returns the canonical WebSocket URL the
client connects to.
A-16 shipped the WS endpoint at that URL with an echo-loop scaffold.
A-18 replaced the echo with the real audio bridge: bytes frames carry
audio, the text control frame `{"type":"audio_end"}` terminates each
utterance, and the server emits `asr_partial` / `asr_final` events
back through `ASRProvider`.
A-19 chained `ModerationService` after each `asr_final` so finalized
transcripts go through the same cascading red-line scoring
`POST /v1/moderation/check` uses; a `moderation` event follows the
`asr_final` so the client can react.
A-20 wired `LLMRouter`. When the moderation verdict is `allow` or
`warn`, a Coach K hint is generated in the background and streamed
back as `hint_delta` / `hint_done` events. `redirect` and `block`
verdicts gate the LLM call entirely — no tokens are spent on
content the platform won't surface.
A-21 (this module) attaches a Langfuse trace per utterance:
`copilot_utterance`-named, with `transcribe` / `moderate` /
`coach_hint` child generations so analysts can see the full pipeline
on the Langfuse UI. When LANGFUSE_PUBLIC_KEY/SECRET_KEY is unset the
trace wrapper degrades to no-op so dev runs keep working.

Compliance attach point (POST)
------------------------------
`require_adult` chains through `require_age_set`, so the failure
ladder is:
  * No token                  → 401 UNAUTHORIZED
  * Token, age_set=False      → 403 AGE_REQUIRED
  * Token, is_minor=True      → 403 MINOR_FORBIDDEN
  * Token, adult, age set     → 200 (real handler runs)

R-15 in PRD §11.2 (未成年人误用副驾) is the load-bearing constraint
that makes the minor gate non-negotiable.

WebSocket auth model (transitional, A-16)
-----------------------------------------
The WS endpoint does NOT re-run `require_adult`. The capability ticket
is the freshly-minted `copilot_id` itself: only a `pending` row can
connect, and `pending` rows can only exist if the POST cleared the
adult gate. A future PR will tighten this with a JWT-bearing
subprotocol once B's client is comfortable signing the WS upgrade.
The 64 bits of entropy on `copilot_id` (16 hex chars) keeps brute-force
mining of valid ids out of reach for v0.

WS protocol — A-18 / A-19 / A-20
--------------------------------
Once connected, the client–server protocol is:

    Client → Server
        binary frame: PCM/Opus audio chunk for the current utterance
        text frame:   JSON `{"type":"audio_end"}` to finalize the
                      current utterance; any other text is ignored

    Server → Client
        text frame:   `{"type":"asr_partial","text":...}`
                      cumulative interim transcript, may revise
        text frame:   `{"type":"asr_final","text":...}`
                      exactly one per utterance, terminal transcript
        text frame:   `{"type":"moderation","verdict":"allow"|"warn"|
                       "redirect"|"block","categories":[...],
                       "score":0..1,"redirect_resource":null|{...}}`
                      follows asr_final when final text is non-empty
        text frame:   `{"type":"hint_delta","text":"chunk"}`
                      LLM token chunk (one per delta from the router)
        text frame:   `{"type":"hint_done","text":"<full text>"}`
                      terminal hint event with the joined transcript
        text frame:   `{"type":"hint_error","message":"..."}`
                      LLM call failed (auth / timeout / upstream)

Hint events only emit when the moderation verdict is `allow` or
`warn`. Hints are generated by a background task, so a slow LLM
doesn't block the next utterance — events for utterance N+1 may
interleave with hint events for utterance N, and the client demuxes
on `type`. The handler awaits all in-flight hint tasks in `finally`
before flipping the row to `ended`.
"""

from __future__ import annotations

import asyncio
import json
import secrets
from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import Any

import structlog
from fastapi import APIRouter, Depends, WebSocket
from langfuse import Langfuse
from starlette.websockets import WebSocketDisconnect

from app.asr import ASRProvider, get_asr_provider
from app.llm import LLMError, LLMProvider, Message
from app.llm.factory import get_llm_router
from app.observability.langfuse import (
    TurnTrace,
    begin_copilot_trace,
    get_langfuse_client,
)
from app.schemas.copilot import CreateCopilotSessionRequest, CreateCopilotSessionResponse
from app.schemas.moderation import ModerationCheckRequest, ModerationVerdict
from app.services.auth import CurrentUser, require_adult
from app.services.copilot import CopilotService, get_copilot_service
from app.services.copilot.service import (
    CopilotSessionNotFound,
    CopilotSessionUnavailable,
)
from app.services.moderation import ModerationService, get_moderation_service
from app.services.moderation.types import Decision

# Stable model labels surfaced on the Langfuse generation rows. The
# moderation pipeline can swap backends per request (CascadingBackend
# falls back local→cloud) so we use a fixed label rather than peeking
# at `_backend.name`.
_MOD_GENERATION_MODEL = "moderation_pipeline"

logger = structlog.get_logger(__name__)

router = APIRouter(prefix="/copilot", tags=["copilot"])

# Application-defined close codes (RFC 6455 §7.4.2 reserves 4000–4999
# for app use). 4404 / 4409 mirror the HTTP status semantics so any
# client that already understands "404 / 409 = retry policy" can map
# them mechanically without a per-feature lookup table.
_WS_UNKNOWN_COPILOT_CODE = 4404
_WS_SESSION_ALREADY_USED_CODE = 4409

_AUDIO_END_TYPE = "audio_end"

# Verdicts that pass the moderation gate and let the LLM hint emit.
# `redirect` already surfaces a crisis-line resource via the moderation
# event itself; `block` is a hard stop. Both suppress hint generation
# so we never spend tokens on content we wouldn't surface.
_HINT_ALLOWED_VERDICTS: frozenset[ModerationVerdict] = frozenset({"allow", "warn"})

COACH_SYSTEM_PROMPT = (
    "你是教练 K — 副驾模式。用户正在真实对话中（场景见上下文），对方刚说了一句话；"
    "请给用户一句 ≤ 40 字的下一句提示，不替用户说话，不爹味说教。"
)


@router.post(
    "/sessions",
    response_model=CreateCopilotSessionResponse,
    summary="Create a realtime copilot session",
    responses={
        401: {"description": "Missing or invalid bearer token."},
        403: {
            "description": (
                "`AGE_REQUIRED` if the JWT lacks `age_set=true`; "
                "`MINOR_FORBIDDEN` if the caller is under 18. PRD §1.5 / R-15."
            ),
        },
    },
)
async def create_copilot_session(
    payload: CreateCopilotSessionRequest,
    current: CurrentUser = Depends(require_adult),
    service: CopilotService = Depends(get_copilot_service),
) -> CreateCopilotSessionResponse:
    """Mint a copilot session row and return the WebSocket URL.

    No LLM call, no moderation in this handler — copilot is
    adult-only (gate-enforced) and the audio + transcript moderation
    runs in the WS handler against each `asr_final` (A-19). A-15
    persists the session intent so the WS endpoint can look it up
    on connect.
    """
    result = await service.create_session(
        scenario_hint=payload.scenario_hint,
        privacy_level=payload.privacy_level,
        user_id=current.user_id,
    )
    return CreateCopilotSessionResponse(
        copilot_id=result.record.copilot_id,
        ws_url=result.ws_url,
    )


@router.websocket("/sessions/{copilot_id}/stream")
async def copilot_stream(
    websocket: WebSocket,
    copilot_id: str,
    service: CopilotService = Depends(get_copilot_service),
    asr_provider: ASRProvider = Depends(get_asr_provider),
    moderation_service: ModerationService = Depends(get_moderation_service),
    llm_router: LLMProvider = Depends(get_llm_router),
    langfuse_client: Langfuse | None = Depends(get_langfuse_client),
) -> None:
    """Realtime copilot stream — audio bridge + moderation + Coach K hints.

    Lifecycle
    ---------
    1. Accept the WS upgrade unconditionally — we always accept first
       so failures send a structured close frame instead of the opaque
       `403` that pre-accept rejection would yield. Clients then know
       how to map our 4xxx codes.
    2. `connect_session` flips the row to `connected` (or raises one
       of the two error types below). The returned record carries the
       JWT-derived `user_id` for moderation audit attribution and the
       `scenario_hint` we feed to Coach K's prompt.
    3. Multi-utterance loop: for each utterance, run the audio bridge
       until `audio_end` or disconnect, moderate the final text, and
       (if verdict allows) spawn a background hint task.
    4. When the NEXT utterance completes, any still-in-flight hints
       from prior utterances are cancelled (A-22) — they're no
       longer relevant once the user has moved on. Tokens already
       streamed to the client stay visible; the missing `hint_done`
       is the client's signal that the prior hint was superseded.
    5. Client disconnect (or any exception) drains in-flight hint
       tasks, then runs `end_session` — flips the row to `ended` and
       stamps `ended_at`.

    `end_session` is only reachable when `connect_session` succeeded:
    the two `except` arms above `close()` and `return` early so an
    unknown-id probe never falls through into the multi-utterance loop
    and never triggers the cleanup `finally`.
    """
    await websocket.accept()
    record = None
    try:
        record = await service.connect_session(copilot_id)
    except CopilotSessionNotFound:
        await websocket.close(
            code=_WS_UNKNOWN_COPILOT_CODE,
            reason="UNKNOWN_COPILOT",
        )
        return
    except CopilotSessionUnavailable:
        await websocket.close(
            code=_WS_SESSION_ALREADY_USED_CODE,
            reason="SESSION_ALREADY_USED",
        )
        return

    hint_tasks: set[asyncio.Task[None]] = set()
    try:
        while True:
            result, trace = await _run_one_utterance(
                websocket,
                asr_provider=asr_provider,
                moderation_service=moderation_service,
                copilot_id=copilot_id,
                user_id=record.user_id,
                scenario_hint=record.scenario_hint,
                privacy_level=record.privacy_level,
                langfuse_client=langfuse_client,
            )
            # The user has moved on to a new utterance; any prior
            # hint that hasn't finished is now stale. Cancel here so
            # the LLM stream stops billing tokens and no further
            # `hint_delta` / `hint_done` events arrive for content
            # the user no longer cares about.
            await _cancel_in_flight_hints(hint_tasks, copilot_id=copilot_id)
            if _should_spawn_hint(result):
                task = asyncio.create_task(
                    _stream_coach_hint(
                        websocket,
                        llm_router=llm_router,
                        scenario_hint=record.scenario_hint,
                        user_input=result.final_text,
                        copilot_id=copilot_id,
                        trace=trace,
                    )
                )
                hint_tasks.add(task)
                task.add_done_callback(hint_tasks.discard)
    except WebSocketDisconnect:
        logger.info("copilot_ws_disconnected", copilot_id=copilot_id)
    finally:
        # Final drain — at session end, prefer cancelling the
        # in-flight LLM call over waiting for it to complete: the user
        # is gone, the WS is closing, no one will see the tokens.
        await _cancel_in_flight_hints(hint_tasks, copilot_id=copilot_id)
        await service.end_session(copilot_id)


async def _cancel_in_flight_hints(
    hint_tasks: set[asyncio.Task[None]],
    *,
    copilot_id: str,
) -> None:
    """Cancel and drain all not-yet-done hint tasks.

    Called between utterances (the new audio supersedes the prior
    hint) and once more in the outer `finally` (session is ending).
    Done tasks are skipped — `task.cancel()` on a finished task is
    a no-op, but `gather` would still re-raise their stored
    exceptions; filtering keeps the gather call clean.

    Errors from cancelled tasks are swallowed: `CancelledError` is
    expected, and any other late-arriving exception was already
    logged by `_stream_coach_hint`'s own try/except.
    """
    pending = [t for t in hint_tasks if not t.done()]
    if not pending:
        return
    for task in pending:
        task.cancel()
    logger.info(
        "copilot_hint_tasks_cancelled",
        copilot_id=copilot_id,
        count=len(pending),
    )
    await asyncio.gather(*pending, return_exceptions=True)


@dataclass(frozen=True)
class _UtteranceResult:
    """Outcome of one `_run_one_utterance` cycle.

    `verdict` is None when the final text was empty (no moderation
    ran, see PRD-aligned skip in `_run_one_utterance`). Callers gate
    on `verdict in _HINT_ALLOWED_VERDICTS` rather than checking
    `final_text` directly so the gate stays in one place.
    """

    final_text: str
    verdict: ModerationVerdict | None


def _should_spawn_hint(result: _UtteranceResult) -> bool:
    return bool(result.final_text) and result.verdict in _HINT_ALLOWED_VERDICTS


async def _run_one_utterance(
    websocket: WebSocket,
    *,
    asr_provider: ASRProvider,
    moderation_service: ModerationService,
    copilot_id: str,
    user_id: str,
    scenario_hint: str,
    privacy_level: str,
    langfuse_client: Langfuse | None,
) -> tuple[_UtteranceResult, TurnTrace]:
    """Receive audio bytes + an `audio_end` control frame, transcribe,
    emit `asr_partial` / `asr_final` events, then run moderation on
    the finalized text and emit a `moderation` event. Returns
    `(_UtteranceResult, TurnTrace)`: the result so the caller can
    decide whether to spawn a hint task, and the trace so the hint
    task can record its generation under the same parent.

    Raises `WebSocketDisconnect` if the client disconnects
    mid-utterance (the trace is marked failed and re-raised).

    Concurrency: feeder and streamer run in parallel via
    `asyncio.gather` because `DummyASRProvider` (and any real vendor)
    yields partials as chunks arrive — we can't feed first then
    stream, or partials would back up unbounded. `gather` cancels the
    other task on first exception, which is the right behavior for a
    `WebSocketDisconnect` from either side.

    Moderation runs serially after the audio loop completes. Hint
    generation (when applicable) is spawned by the caller as a
    background task, so a slow LLM doesn't block the next utterance.
    The hint task records its own generation on the trace; the trace
    output is set here based on the moderation outcome, and the hint
    arrives later as an additional child span (Langfuse handles that
    cleanly — `update(output=...)` doesn't close the trace).
    """
    audio_queue: asyncio.Queue[bytes | None] = asyncio.Queue()

    async def audio_iter() -> AsyncIterator[bytes]:
        while True:
            chunk = await audio_queue.get()
            if chunk is None:
                return
            yield chunk

    feeder = _feed_audio(websocket, audio_queue, copilot_id)
    streamer = _stream_asr_events(websocket, asr_provider, audio_iter(), copilot_id)
    # If the client disconnects mid-utterance, gather raises
    # WebSocketDisconnect from the feeder; we do NOT mint a trace
    # for that case — the outer handler logs the disconnect and
    # an empty Langfuse trace would just be noise.
    _, final_text = await asyncio.gather(feeder, streamer)

    trace = begin_copilot_trace(
        langfuse_client,
        input={"scenario_hint": scenario_hint},
        # `copilot_id` is promoted to Langfuse's top-level session_id
        # (A-23) so every utterance in one WS connection lands under
        # the same Langfuse session. Keep `user_id` in metadata for
        # cross-session filtering.
        metadata={"user_id": user_id},
        session_id=copilot_id,
        # A-24: surface + privacy tags at creation. Verdict tag is
        # added after moderation runs (below). `minor:false` is
        # implicit and intentionally NOT tagged — copilot is
        # adult-only by R-15.
        tags=[
            "surface:copilot",
            f"privacy:{privacy_level}",
        ],
    )
    trace.record_generation(
        name="transcribe",
        model=asr_provider.name,
        input={"copilot_id": copilot_id},
        output={"text": final_text, "char_count": len(final_text)},
    )

    if not final_text:
        trace.finish(output={"final_text": "", "verdict": None})
        return _UtteranceResult(final_text="", verdict=None), trace

    decision = await _moderate_and_emit(
        websocket,
        moderation_service=moderation_service,
        text=final_text,
        copilot_id=copilot_id,
        user_id=user_id,
    )
    if decision is not None:
        trace.record_generation(
            name="moderate",
            model=_MOD_GENERATION_MODEL,
            input={"text": final_text},
            output={
                "verdict": decision.verdict,
                "score": decision.score,
                "categories": list(decision.categories),
            },
        )
        # A-24: verdict tag added now that moderation has run. Lets
        # analysts filter for traces that hit a particular outcome
        # (e.g. all `verdict:redirect` for crisis-line escalations).
        trace.add_tags([f"verdict:{decision.verdict}"])

    verdict = decision.verdict if decision is not None else None
    trace.finish(output={"final_text": final_text, "verdict": verdict})
    return _UtteranceResult(final_text=final_text, verdict=verdict), trace


async def _feed_audio(
    websocket: WebSocket,
    audio_queue: asyncio.Queue[bytes | None],
    copilot_id: str,
) -> None:
    """Pull frames off the WS and feed audio bytes into the queue.
    Returns when `audio_end` arrives; raises `WebSocketDisconnect` on
    client disconnect (and puts a None sentinel so the ASR iterator
    unblocks before we propagate)."""
    while True:
        msg = await websocket.receive()
        if msg["type"] == "websocket.disconnect":
            await audio_queue.put(None)
            raise WebSocketDisconnect(code=msg.get("code", 1000))

        chunk: bytes | None = msg.get("bytes")
        if chunk is not None:
            await audio_queue.put(chunk)
            continue

        text: str | None = msg.get("text")
        if text is not None and _is_audio_end(text):
            await audio_queue.put(None)
            return
        if text is not None:
            logger.debug(
                "copilot_ws_unknown_text_frame",
                copilot_id=copilot_id,
                preview=text[:80],
            )


async def _stream_asr_events(
    websocket: WebSocket,
    asr_provider: ASRProvider,
    audio_chunks: AsyncIterator[bytes],
    copilot_id: str,
) -> str:
    """Consume the ASR provider's event stream, forward each event as
    a typed WS envelope, and return the final transcript text so the
    caller can run moderation + hint generation on it."""
    final_text = ""
    async for event in asr_provider.transcribe_stream(audio_chunks):
        await websocket.send_json(
            {
                "type": f"asr_{event.kind}",
                "text": event.text,
            }
        )
        if event.kind == "final":
            final_text = event.text
    logger.info(
        "copilot_ws_utterance_complete",
        copilot_id=copilot_id,
        provider=asr_provider.name,
        final_char_count=len(final_text),
    )
    return final_text


async def _moderate_and_emit(
    websocket: WebSocket,
    *,
    moderation_service: ModerationService,
    text: str,
    copilot_id: str,
    user_id: str,
) -> Decision | None:
    """Score the finalized transcript and emit a `moderation` event.

    Returns the underlying `Decision` so the caller can gate
    downstream work (hint generation) on the verdict. Returns None if
    the moderation call itself raised — the WS stays open and we just
    skip the gate (downstream hint won't spawn since None isn't in
    the allowed set).

    Strictness
    ----------
    `is_minor=False` is hardcoded because copilot is adult-only — the
    POST handler's `require_adult` guarantees no minor JWT can mint a
    pending session in the first place. If a future PR widens copilot
    to teens (it shouldn't — R-15) this needs to plumb the flag from
    the JWT through the session record.
    """
    trace_id = "cop_mod_" + secrets.token_hex(8)
    request = ModerationCheckRequest(content=text, context="user_input")
    try:
        response = await moderation_service.check(
            request,
            user_id=user_id,
            is_minor=False,
            trace_id=trace_id,
        )
    except Exception:
        logger.exception(
            "copilot_moderation_failed",
            copilot_id=copilot_id,
            trace_id=trace_id,
        )
        return None

    payload: dict[str, Any] = {
        "type": "moderation",
        "verdict": response.verdict,
        "categories": response.categories,
        "score": response.score,
        "redirect_resource": (
            response.redirect_resource.model_dump()
            if response.redirect_resource is not None
            else None
        ),
    }
    await websocket.send_json(payload)

    return Decision(
        verdict=response.verdict,
        score=response.score,
        categories=tuple(response.categories),
        redirect_resource=response.redirect_resource,
    )


async def _stream_coach_hint(
    websocket: WebSocket,
    *,
    llm_router: LLMProvider,
    scenario_hint: str,
    user_input: str,
    copilot_id: str,
    trace: TurnTrace,
) -> None:
    """Generate a Coach K hint for one utterance and stream it back.

    Runs as a background task — concurrent with the next utterance's
    audio loop. Each delta arrives as `{"type":"hint_delta","text":...}`;
    the joined transcript closes the run as `{"type":"hint_done","text":...}`.

    Empty hints emit nothing. The router yielding zero non-empty
    chunks (rare, but possible with a misbehaving prompt or upstream)
    converges on "no events" rather than an empty `hint_done` so the
    client's UI doesn't flash a blank tip card.

    Records a `coach_hint` generation on the parent utterance trace
    iff the call produced any text. LLM-error paths skip the
    generation — the failure is captured by the structured log and
    the `hint_error` event the user sees; an extra empty Langfuse
    span would be noise.

    Failure modes
    -------------
      * `LLMError` (auth / timeout / upstream)  → log + emit one
        `hint_error` event with a stable opaque message; the WS stays
        open so the user can keep speaking.
      * WS already closed when we try to send → return silently. The
        outer handler will await this task in `finally` and discard
        the return value.
    """
    messages: list[Message] = [
        Message.system(COACH_SYSTEM_PROMPT),
        Message.user(_build_coach_user_prompt(scenario_hint, user_input)),
    ]
    parts: list[str] = []
    try:
        async for chunk in llm_router.stream_chat(messages):
            if not chunk:
                continue
            if not await _send_or_drop(
                websocket,
                {"type": "hint_delta", "text": chunk},
                copilot_id=copilot_id,
            ):
                return
            parts.append(chunk)
    except LLMError:
        logger.exception("copilot_hint_llm_failed", copilot_id=copilot_id)
        await _send_or_drop(
            websocket,
            {"type": "hint_error", "message": "hint unavailable"},
            copilot_id=copilot_id,
        )
        return

    full = "".join(parts)
    if not full:
        return
    trace.record_generation(
        name="coach_hint",
        model=llm_router.name,
        input={"scenario_hint": scenario_hint, "user_input": user_input},
        output={"text": full},
    )
    await _send_or_drop(
        websocket,
        {"type": "hint_done", "text": full},
        copilot_id=copilot_id,
    )


def _build_coach_user_prompt(scenario_hint: str, user_input: str) -> str:
    return (
        f"用户当前场景：{scenario_hint}\n对方刚说：「{user_input}」\n请给用户一句下一句话的提示。"
    )


async def _send_or_drop(
    websocket: WebSocket,
    payload: dict[str, Any],
    *,
    copilot_id: str,
) -> bool:
    """Send a hint event, returning False if the WS is already closed.

    Background hint tasks may outlive the active connection (the user
    disconnects mid-hint). We don't want a routine WS-closed exception
    to bubble up — log it once and return False so the caller stops
    sending more.
    """
    try:
        await websocket.send_json(payload)
        return True
    except Exception:
        logger.info(
            "copilot_hint_send_dropped",
            copilot_id=copilot_id,
            payload_type=payload.get("type"),
        )
        return False


def _is_audio_end(raw: str) -> bool:
    """`{"type":"audio_end"}` is the only text control frame the
    bridge currently recognises. Robust against malformed JSON and
    unexpected shapes — anything we don't understand is silently
    dropped at the call site."""
    try:
        data: Any = json.loads(raw)
    except json.JSONDecodeError:
        return False
    return isinstance(data, dict) and data.get("type") == _AUDIO_END_TYPE
